# Generated by Django 5.2.6 on 2025-09-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('product_type', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
