# Generated by Django 5.2.6 on 2025-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_product_image_alter_product_gtin_alter_product_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
